FROM node:24-alpine3.21 as build
WORKDIR /app

ARG REACT_APP_EXTERNAL_SERVICES_SPEC_ID=""
ARG REACT_APP_PARENT_ORGANISATION_ID=""
ARG REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY=""
ARG REACT_APP_DATABASE_ID=""
ARG REACT_APP_ADMIN_SOLUTION_AUTH_TOKEN=""
ARG REACT_APP_ROLE_ADMINISTRATOR=""
ARG REACT_APP_ROLE_CHIEF_OF_SERVICE=""
ARG REACT_APP_ROLE_CITY_WORKER=""
ARG REACT_APP_BACKEND_API=""
ARG REACT_APP_EMAIL_AUTH_CODE_ADMIN_FR=""
ARG REACT_APP_EMAIL_AUTH_CODE_ADMIN_NL=""
ARG REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_FR=""
ARG REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_NL=""
ARG REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_FR=""
ARG REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_NL=""
ARG REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_FR=""
ARG REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_NL=""

ENV PATH=/app/node_modules/.bin:$PATH
ENV REACT_APP_EXTERNAL_SERVICES_SPEC_ID=$REACT_APP_EXTERNAL_SERVICES_SPEC_ID
ENV REACT_APP_PARENT_ORGANISATION_ID=$REACT_APP_PARENT_ORGANISATION_ID
ENV REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY=$REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY
ENV REACT_APP_DATABASE_ID=$REACT_APP_DATABASE_ID
ENV REACT_APP_ADMIN_SOLUTION_AUTH_TOKEN=$REACT_APP_ADMIN_SOLUTION_AUTH_TOKEN
ENV REACT_APP_ROLE_ADMINISTRATOR=$REACT_APP_ROLE_ADMINISTRATOR
ENV REACT_APP_ROLE_CHIEF_OF_SERVICE=$REACT_APP_ROLE_CHIEF_OF_SERVICE
ENV REACT_APP_ROLE_CITY_WORKER=$REACT_APP_ROLE_CITY_WORKER
ENV REACT_APP_BACKEND_API=$REACT_APP_BACKEND_API
ENV REACT_APP_EMAIL_AUTH_CODE_ADMIN_FR=$REACT_APP_EMAIL_AUTH_CODE_ADMIN_FR
ENV REACT_APP_EMAIL_AUTH_CODE_ADMIN_NL=$REACT_APP_EMAIL_AUTH_CODE_ADMIN_NL
ENV REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_FR=$REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_FR
ENV REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_NL=$REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_NL
ENV REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_FR=$REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_FR
ENV REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_NL=$REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_NL
ENV REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_FR=$REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_FR
ENV REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_NL=$REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_NL

COPY package.json /app/package.json
COPY . /app
RUN corepack enable
RUN yarn install
RUN NODE_OPTIONS="--max_old_space_size=4096" yarn run build

FROM nginx:1.29.2-alpine
COPY /docker/nginx*.conf /etc/nginx/
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
