export const ICURE_NIGHTLY_URL = window.config.REACT_APP_ICURE_NIGHTLY_URL
export const ICURE_API_URL = window.config.REACT_APP_ICURE_API_URL
export const MSG_GW_URL = window.config.REACT_APP_MSG_GW_URL
export const SPEC_ID = window.config.REACT_APP_EXTERNAL_SERVICES_SPEC_ID
export const PARENT_ORGANISATION_ID = window.config.REACT_APP_PARENT_ORGANISATION_ID
export const FRIENDLY_CAPTCHA_SITE_KEY = window.config.REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY
export const DATABASE_ID = window.config.REACT_APP_DATABASE_ID
export const ROLE_ADMINISTRATOR = window.config.REACT_APP_ROLE_ADMINISTRATOR
export const ROLE_CHIEF_OF_SERVICE = window.config.REACT_APP_ROLE_CHIEF_OF_SERVICE
export const ROLE_CITY_WORKER = window.config.REACT_APP_ROLE_CITY_WORKER
export const BACKEND_API = window.config.REACT_APP_BACKEND_API
export const EMAIL_SENDER = window.config.REACT_APP_EMAIL_SENDER
export const EMAIL_AUTH_CODE_CITIZEN_FR = window.config.REACT_APP_EMAIL_AUTH_CODE_CITIZEN_FR
export const EMAIL_AUTH_CODE_CITIZEN_NL = window.config.REACT_APP_EMAIL_AUTH_CODE_CITIZEN_NL
export const EMAIL_CONFIRMATION_CODE_FR = window.config.REACT_APP_EMAIL_CONFIRMATION_CODE_FR
export const EMAIL_CONFIRMATION_CODE_NL = window.config.REACT_APP_EMAIL_CONFIRMATION_CODE_NL
export const EMAIL_APPOINTMENT_CONFIRMATION_FR = window.config.REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_FR
export const EMAIL_APPOINTMENT_CONFIRMATION_NL = window.config.REACT_APP_EMAIL_APPOINTMENT_CONFIRMATION_NL
export const EMAIL_APPOINTMENT_CANCELLATION_FR = window.config.REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_FR
export const EMAIL_APPOINTMENT_CANCELLATION_NL = window.config.REACT_APP_EMAIL_APPOINTMENT_CANCELLATION_NL
export const EMAIL_APPOINTMENT_MODIFICATION_FR = window.config.REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_FR
export const EMAIL_APPOINTMENT_MODIFICATION_NL = window.config.REACT_APP_EMAIL_APPOINTMENT_MODIFICATION_NL
export const BASE_PATH = window.location.origin

export const ADMIN_SOLUTIONS_AUTH_TOKEN = ''
export const ADMIN_SOLUTIONS_EMAIL = ''
export const EMAIL_TEMPLATE = 'ec7d9b00-948c-11f0-a83d-fffe07e305e2'

export enum RootHcpType {
  SITE_ROOT = 'site-root',
  ADMIN_ROOT = 'admin-root',
}
