steps:
  -   name: 'gcr.io/cloud-builders/git'
      entrypoint: 'bash'
      args: [ '-c', 'git fetch --unshallow --tags && git checkout ${BRANCH_NAME} && git submodule init && git submodule update' ]

  -   name: 'docker'
      args: [ "build", "--build-arg", "REACT_APP_EXTERNAL_SERVICES_SPEC_ID=${_REACT_APP_EXTERNAL_SERVICES_SPEC_ID}", "--build-arg", "REACT_APP_EMAIL_AUTHENTICATION_PROCESS_ID=${_REACT_APP_EMAIL_AUTHENTICATION_PROCESS_ID}", "--build-arg", "REACT_APP_PARENT_ORGANISATION_ID=${_REACT_APP_PARENT_ORGANISATION_ID}","--build-arg", "REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY=${_REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY}", "-t", "docker.taktik.be/icure-ehr-lite-doctor-app", "." ]

  -   name: 'docker.taktik.be/ticketing-agenda'
      entrypoint: sh
      args: [ '-c', 'cp -af /app/build /workspace' ]

  -   name: 'gcr.io/cloud-builders/gsutil'
      args: ["-m", "rsync", "-r", "-c", "-d", "./build", "${_DEPLOY}"]

timeout: 1800s
