steps:
  -   name: 'gcr.io/cloud-builders/git'
      entrypoint: 'bash'
      args: [ '-c', 'git fetch --unshallow --tags && git checkout $BRANCH_NAME' ]

  -   name: 'taktik/git-version:2.0.21-g2f3751c36c'
      args: [ '-f', 'git.version' ]

  -   id: 'login'
      name: 'docker:27'
      entrypoint: 'sh'
      args: [ '-c', 'echo $$REPO_PASSWORD | docker login docker.taktik.be --username=$$REPO_USERNAME --password-stdin' ]
      secretEnv: [ 'REPO_USERNAME', 'REPO_PASSWORD' ]

  -   id: 'frontend'
      waitFor: [ 'login' ]
      name: 'docker:27'
      entrypoint: 'sh'
      args: [ '-c', 'docker build --progress=plain --push -t docker.taktik.be/mouscron/ticketing-agenda:$(cat git.version) --build-arg "version=$(cat git.version)" --build-arg "REACT_APP_EXTERNAL_SERVICES_SPEC_ID=${_REACT_APP_EXTERNAL_SERVICES_SPEC_ID}" --build-arg "REACT_APP_EMAIL_AUTHENTICATION_PROCESS_ID=${_REACT_APP_EMAIL_AUTHENTICATION_PROCESS_ID}" --build-arg "REACT_APP_PARENT_ORGANISATION_ID=${_REACT_APP_PARENT_ORGANISATION_ID}" --build-arg "REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY=${_REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY}" --build-arg "REACT_APP_DATABASE_ID=${_REACT_APP_DATABASE_ID}" --build-arg "REACT_APP_ADMIN_SOLUTION_AUTH_TOKEN=${_REACT_APP_ADMIN_SOLUTION_AUTH_TOKEN}" --build-arg "REACT_APP_ROLE_ADMINISTRATOR=${_REACT_APP_ROLE_ADMINISTRATOR}" --build-arg "REACT_APP_ROLE_CHIEF_OF_SERVICE=${_REACT_APP_ROLE_CHIEF_OF_SERVICE}" --build-arg "REACT_APP_ROLE_CITY_WORKER=${_REACT_APP_ROLE_CITY_WORKER}" --build-arg "REACT_APP_TAKTIK_API=${_REACT_APP_TAKTIK_API}" .' ]

  -   name: 'alpine/helm'
      entrypoint: 'sh'
      args: [ '-c', 'v=$(cat git.version) && helm package ./deployment/helm/mouscron-agenda --version $v --app-version $v -d . && apk --no-cache add curl && curl -F file=@./mouscron-agenda-${v}.tgz -u $$REPO_USERNAME:$$REPO_PASSWORD "https://helm.taktik.be/service/rest/v1/components?repository=helm"' ]
      secretEnv: [ 'REPO_USERNAME', 'REPO_PASSWORD' ]

availableSecrets:
  secretManager:
    -   versionName: projects/taktik-dev/secrets/ci-repo-username/versions/1
        env: 'REPO_USERNAME'
    -   versionName: projects/taktik-dev/secrets/ci-repo-password/versions/1
        env: 'REPO_PASSWORD'

logsBucket: 'gs://taktik-build-logs'
options:
  logging: GCS_ONLY
timeout: 900s
